### PR TITLE
correct subsampling calculate methods of various fourcc that jpeg sup…

### LINKED ISSUE #10: loadjpeg will crash for ffmpeg generated content
migrated from Bugzilla [#97633](https://bugs.freedesktop.org/show_bug.cgi?id=97633)
status ASSIGNED severity *normal* in component *intel* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: PengChen

Original attachment names and IDs:
- _[16x16_422P.jpeg](https://bugs.freedesktop.org//attachment.cgi?id=126296)_ (ID 126296)
- _[16x16_440P.jpeg](https://bugs.freedesktop.org//attachment.cgi?id=126297)_ (ID 126297)
- _[16x16_444P.jpeg](https://bugs.freedesktop.org//attachment.cgi?id=126298)_ (ID 126298)

On 2016-09-08 09:12:54 +0000, Guangxin.Xu wrote:

> Created attachment 126296
> 422H
> 
> loadjpeg will crash at gen75_mfd_jpeg_decode_init L2201
> 
> 
> # 4  0x00007ffff5497bc4 in gen75_mfd_jpeg_decode_init (decode_state=0x616388, decode_state=0x616388, gen7_mfd_context=0x61cd00, ctx=0x612180) at gen75_mfd.c:2201
> 2201                assert(0);
> (gdb) l
> 2196            } else if (h1 == 2 && h2 == 2 && h3 == 2 &&
> 2197                       v1 == 2 && v2 == 1 && v3 == 1) {
> 2198                subsampling = SUBSAMPLE_YUV422V;
> 2199                fourcc = VA_FOURCC_422V;
> 2200            } else
> 2201                assert(0);
> 2202        } else {
> 2203            assert(0);
> 2204        }

On 2016-09-08 09:13:28 +0000, Guangxin.Xu wrote:

> Created attachment 126297
> 44V

On 2016-09-08 09:13:48 +0000, Guangxin.Xu wrote:

> Created attachment 126298
> 444P

### PR DESCRIPTION
**Pull request by laureatian**
…port. This fixes #10 https://github.com/01org/intel-vaapi-driver/issues/10

Signed-off-by: Wang Tiantian <tiantian.wang@intel.com>

### CODE REVIEW

**Comment by xhaihao** [comment]
Could you separate the summary from the body in the log?

File: src/gen7_mfd.c [hunk 1]
```diff
@@ -1853,37 +1853,30 @@ gen7_mfd_jpeg_decode_init(VADriverContextP ctx,
...
+        } else if (h1 == h2 && h2 == h3 &&
+                   v1 == 2 * v2 && v2 == v3) {
             subsampling = SUBSAMPLE_YUV422V;
             fourcc = VA_FOURCC_422V;
         } else
             assert(0);
-    } else {
+    }
+    else {
         assert(0);
```
Comment (xhaihao) [inline src/gen7_mfd.c]: Please rebase your branch against github.com:01org/intel-vaapi-driver.git, and run ./autogen.sh to install the pre-commit hook which will check your coding style. then commit your change again.

File: src/gen75_mfd.c [hunk 2]
```diff
@@ -2262,17 +2254,17 @@ gen75_mfd_jpeg_pic_state(VADriverContextP ctx,
         int v2 = pic_param->components[1].v_sampling_factor;
         int v3 = pic_param->components[2].v_sampling_factor;
 
-        if (h1 == 2 && h2 == 1 && h3 == 1 &&
-            v1 == 2 && v2 == 1 && v3 == 1)
+        if (h1 == 2 * h2 && h2 == h3 &&
+            v1 == 2 *v2 && v2 == v3)
             chroma_type = GEN7_YUV420;
         else if (h1 == 2 && h2 == 1 && h3 == 1 &&
                  v1 == 1 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen75_mfd.c]: Is a fix to this condition also needed?

File: src/gen75_mfd.c [hunk 3]
```diff
@@ -2262,17 +2254,17 @@ gen75_mfd_jpeg_pic_state(VADriverContextP ctx,
...
+        else if (h1 == h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV444;
-        else if (h1 == 4 && h2 == 1 && h3 == 1 &&
-                 v1 == 1 && v2 == 1 && v3 == 1)
+        else if (h1 == 4 * h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV411;
         else if (h1 == 1 && h2 == 1 && h3 == 1 &&
                  v1 == 2 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen75_mfd.c]: Is a fix to this condition also needed?

File: src/gen7_mfd.c [hunk 4]
```diff
@@ -1946,17 +1939,17 @@ gen7_mfd_jpeg_pic_state(VADriverContextP ctx,
         int v2 = pic_param->components[1].v_sampling_factor;
         int v3 = pic_param->components[2].v_sampling_factor;
 
-        if (h1 == 2 && h2 == 1 && h3 == 1 &&
-            v1 == 2 && v2 == 1 && v3 == 1)
+         if (h1 == 2 * h2 && h2 == h3 &&
+            v1 == 2 *v2 && v2 == v3)
             chroma_type = GEN7_YUV420;
         else if (h1 == 2 && h2 == 1 && h3 == 1 &&
                  v1 == 1 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen7_mfd.c]: Is a fix to this condition also needed?

File: src/gen7_mfd.c [hunk 5]
```diff
@@ -1946,17 +1939,17 @@ gen7_mfd_jpeg_pic_state(VADriverContextP ctx,
...
+        else if (h1 == h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV444;
-        else if (h1 == 4 && h2 == 1 && h3 == 1 &&
-                 v1 == 1 && v2 == 1 && v3 == 1)
+        else if (h1 == 4 * h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV411;
         else if (h1 == 1 && h2 == 1 && h3 == 1 &&
                  v1 == 2 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen7_mfd.c]: Is a fix to this condition also needed?

File: src/gen8_mfd.c [hunk 6]
```diff
@@ -1999,17 +1991,17 @@ gen8_mfd_jpeg_pic_state(VADriverContextP ctx,
         int v2 = pic_param->components[1].v_sampling_factor;
         int v3 = pic_param->components[2].v_sampling_factor;
 
-        if (h1 == 2 && h2 == 1 && h3 == 1 &&
-            v1 == 2 && v2 == 1 && v3 == 1)
+        if (h1 == 2 * h2 && h2 == h3 &&
+            v1 == 2 *v2 && v2 == v3)
             chroma_type = GEN7_YUV420;
         else if (h1 == 2 && h2 == 1 && h3 == 1 &&
                  v1 == 1 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen8_mfd.c]: Is a fix to this condition also needed?

File: src/gen8_mfd.c [hunk 7]
```diff
@@ -1999,17 +1991,17 @@ gen8_mfd_jpeg_pic_state(VADriverContextP ctx,
...
+        else if (h1 == h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV444;
-        else if (h1 == 4 && h2 == 1 && h3 == 1 &&
-                 v1 == 1 && v2 == 1 && v3 == 1)
+        else if (h1 == 4 * h2 && h2 == h3 &&
+                 v1 == v2 && v2 == v3)
             chroma_type = GEN7_YUV411;
         else if (h1 == 1 && h2 == 1 && h3 == 1 &&
                  v1 == 2 && v2 == 1 && v3 == 1)
```
Comment (xhaihao) [inline src/gen8_mfd.c]: Is a fix to this condition also needed?
