### PR TITLE
Fix the quality range regression issue

### LINKED ISSUE #72: Unittest Regression: AVCEncode/AVCEContextTest.QualityRange test cases
PR #33 caused the `AVCEncode/AVCEContextTest.QualityRange` unittests to regress in the `test_i965_drv_video` test suite on SKL+.  Based on the nature of the change, this only appears to be an issue with the test cases being out of date now.  That is, the default quality ranges for AVCE were changed in PR #33 but the test cases were not updated to reflect the new defaults.  The good thing is that the test cases reveal that the new changes in the driver are working... just that the expected values are no longer correct for the tests.  Please update these tests to fix this.

```
$ ./test/test_i965_drv_video --gtest_filter=AVCEncode/AVCEContextTest.QualityRange*

Note: Google Test filter = AVCEncode/AVCEContextTest.QualityRange*
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
Seeded std::rand() with 1488480252.
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /opt/media/build/intel-vaapi-driver/src/.libs/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
[----------] 8 tests from AVCEncode/AVCEContextTest
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/0
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 2
To be equal to: hw_context->quality_range
      Which is: 8
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/0, where GetParam() = (VAProfileH264ConstrainedBaseline, VAEntrypointEncSlice) (0 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/1
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 8
To be equal to: hw_context->quality_range
      Which is: 2
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/1, where GetParam() = (VAProfileH264ConstrainedBaseline, VAEntrypointEncSliceLP) (0 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/2
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 2
To be equal to: hw_context->quality_range
      Which is: 8
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/2, where GetParam() = (VAProfileH264Main, VAEntrypointEncSlice) (1 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/3
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 8
To be equal to: hw_context->quality_range
      Which is: 2
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/3, where GetParam() = (VAProfileH264Main, VAEntrypointEncSliceLP) (0 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/4
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 2
To be equal to: hw_context->quality_range
      Which is: 8
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/4, where GetParam() = (VAProfileH264High, VAEntrypointEncSlice) (0 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/5
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 8
To be equal to: hw_context->quality_range
      Which is: 2
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/5, where GetParam() = (VAProfileH264High, VAEntrypointEncSliceLP) (0 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/6
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 1
To be equal to: hw_context->quality_range
      Which is: 8
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/6, where GetParam() = (VAProfileH264MultiviewHigh, VAEntrypointEncSlice) (1 ms)
[ RUN      ] AVCEncode/AVCEContextTest.QualityRange/7
i965_avce_context_test.cpp:240: Failure
      Expected: qranges.at(profile)
      Which is: 1
To be equal to: hw_context->quality_range
      Which is: 8
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/7, where GetParam() = (VAProfileH264StereoHigh, VAEntrypointEncSlice) (0 ms)
[----------] 8 tests from AVCEncode/AVCEContextTest (2 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (19 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/0, where GetParam() = (VAProfileH264ConstrainedBaseline, VAEntrypointEncSlice)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/1, where GetParam() = (VAProfileH264ConstrainedBaseline, VAEntrypointEncSliceLP)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/2, where GetParam() = (VAProfileH264Main, VAEntrypointEncSlice)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/3, where GetParam() = (VAProfileH264Main, VAEntrypointEncSliceLP)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/4, where GetParam() = (VAProfileH264High, VAEntrypointEncSlice)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/5, where GetParam() = (VAProfileH264High, VAEntrypointEncSliceLP)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/6, where GetParam() = (VAProfileH264MultiviewHigh, VAEntrypointEncSlice)
[  FAILED  ] AVCEncode/AVCEContextTest.QualityRange/7, where GetParam() = (VAProfileH264StereoHigh, VAEntrypointEncSlice)
```

### PR DESCRIPTION
**Pull request by QuPengfei**
Fixed #72

Fix the quality range regression issue

### CODE REVIEW

File: test/i965_avce_context_test.cpp [hunk 1]
```diff
@@ -228,6 +233,16 @@ TEST_P(AVCEContextTest, QualityRange)
...
+    const std::map<VAProfile, unsigned> qranges_skl_bxt = {
+        {VAProfileH264ConstrainedBaseline, entrypoint == VAEntrypointEncSliceLP
+            ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
+        {VAProfileH264Main, entrypoint == VAEntrypointEncSliceLP
+            ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
+        {VAProfileH264High, entrypoint == VAEntrypointEncSliceLP
+            ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
+        {VAProfileH264MultiviewHigh, ENCODER_QUALITY_RANGE_AVC},
+        {VAProfileH264StereoHigh, ENCODER_QUALITY_RANGE_AVC},
+    };
```
Comment (uartie) [inline test/i965_avce_context_test.cpp]: Perhaps just declare one map instead of two and assign its values conditionally...

```
std::map<VAProfile, unsigned> qranges;
if (is_skl_bxt) {
       qranges = {
            {VAProfileH264ConstrainedBaseline, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
            {VAProfileH264Main, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
            {VAProfileH264High, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE_AVC},
            {VAProfileH264MultiviewHigh, ENCODER_QUALITY_RANGE_AVC},
            {VAProfileH264StereoHigh, ENCODER_QUALITY_RANGE_AVC},
        };
} else {
      qranges = {
            {VAProfileH264ConstrainedBaseline, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE},
            {VAProfileH264Main, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE},
            {VAProfileH264High, entrypoint == VAEntrypointEncSliceLP
                ? ENCODER_LP_QUALITY_RANGE : ENCODER_QUALITY_RANGE},
            {VAProfileH264MultiviewHigh, 1u},
            {VAProfileH264StereoHigh, 1u},
        };
}

File: test/i965_avce_context_test.cpp [hunk 2]
```diff
@@ -72,6 +76,7 @@ class AVCEContextTest
     VAEntrypoint    entrypoint;
     VAConfigID      config = VA_INVALID_ID;
     VAContextID     context = VA_INVALID_ID;
+    unsigned        is_skl_bxt = 0u;
```
Comment (QuPengfei) [inline test/i965_avce_context_test.cpp]: sure.

File: test/i965_avce_context_test.cpp (hunk 1 above)
Comment (QuPengfei) [inline test/i965_avce_context_test.cpp]: yes, it looks better.

**Comment by QuPengfei** [comment]
update the patch.

Note:
use bool to define the member
define the one map data for quality range according to the platform type

**Comment by xhaihao** [comment]
@QuPengfei, What is the last line in your commit message? Please double check your commit log before submit a PR request.

**Comment by xhaihao** [comment]
and please add a Signed-off-by tag.

**Comment by uartie** [comment]
@xhaihao good catch... sorry i missed that before merge.   I will pay more attention next time.

**Comment by QuPengfei** [comment]
sorry for typo. upstate the commit message header. Please revise it.

**Comment by QuPengfei** [comment]
Fix the quality range regression issue

    v1:
    use bool to define the member
    define the one map data for quality range according to the platform type

    Fixed #72

    Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>

**Comment by xhaihao** [comment]
@QuPengfei It is unnecessary to change the current commit, otherwise we have to revert the current commit or reset the git HEAD first. What I mean is to double check the commit log when you submit a ***new*** PR :)

**Comment by QuPengfei** [comment]
Yes, i will double check in the next time.
