### PR TITLE
Fix: AVC encoder use at most 4 fwd ref frames and 1 bwd ref frames

### LINKED ISSUE #272: [SKL] H264 encoder multi-reference output video mosaic when refs > 5
Used gstreamer-vaapi do transcode h264 to h264 , when set refs value > 5 , the output video has mosaic 

command : gst-launch-1.0 filesrc blocksize=10000000 location=/home/media/zhouyun/skyfall2-trailer.mp4 ! queue ! qtdemux ! vaapih264dec ! queue ! vaapih264enc refs=6 ! mpegtsmux ! filesink location=test.ts

gstreamer-vaapi version : 2eb2b26ad8d8c3fe9233c9242ae37ebdcec89a3c(libs: decoder: at update_caps() decode codec_data)
kernel version : 4.10.0-33-generic
libva version : 1.8.4.pre1
inter-vaapi-driver version : d22e4ef46924715c475c414c6c5c1f060ff286d8

### PR DESCRIPTION
**Pull request by QuPengfei**
Fixes #272

Signed-off-by: Pengfei Qu <Pengfei.Qu@intel.com>

### CODE REVIEW

File: src/i965_drv_video.c [hunk 1]
```diff
@@ -1044,7 +1044,7 @@ i965_GetConfigAttributes(VADriverContextP ctx,
                     profile == VAProfileH264StereoHigh ||
                     profile == VAProfileH264MultiviewHigh) {
                     if (IS_GEN9(i965->intel.device_info))
-                        attrib_list[i].value = (2 << 16) | (8 << 0);
+                        attrib_list[i].value = (1 << 16) | (4 << 0);
```
Comment (xhaihao) [inline src/i965_drv_video.c]: Does AVC encoder support 4 fwd and 1 bwd ref frames for BDW/BSW? BDW/BSW also use the new shaders now

Comment (xhaihao) [reply src/i965_drv_video.c]: @QuPengfei could you update the patch for BDW/BSW too?

Comment (QuPengfei) [reply src/i965_drv_video.c]: add support for BDW/BSW. thanks
