### PR TITLE
Fix AUD insert issue in AVC encoder with GEN6/7.5/8.

### LINKED ISSUE #155: [BSW] Insert AUD has wrong order in AVC encoder
More information, you can refer to: 

https://patchwork.ffmpeg.org/patch/3544/

I know the commit fd52137 fix this issue in GEN9 (I've verified in SKL with master branch), but GEN8 don't have this fix.

### PR DESCRIPTION
**Pull request by mypopydev**
If find the AUD NAL in raw data list, it will insert AUD first in
the bitstream.

Fix #155

Signed-off-by: Jun Zhao <jun.zhao@intel.com>

### CODE REVIEW

File: src/gen6_mfc.c [hunk 1]
```diff
@@ -1404,7 +1406,7 @@ gen6_mfc_pipeline(VADriverContextP ctx,
         vaStatus = gen6_mfc_avc_encode_picture(ctx, encode_state, encoder_context);
         break;
 
-        /* FIXME: add for other profile */
+    /* FIXME: add for other profile */
```
Comment (xhaihao) [inline src/gen6_mfc.c]: Please remove this comment, nothing is required for other profile now.

File: src/gen75_mfc.c [hunk 2]
```diff
@@ -2527,7 +2531,7 @@ static VAStatus gen75_mfc_pipeline(VADriverContextP ctx,
         vaStatus = gen75_mfc_avc_encode_picture(ctx, encode_state, encoder_context);
         break;
 
-        /* FIXME: add for other profile */
+    /* FIXME: add for other profile */
```
Comment (xhaihao) [inline src/gen75_mfc.c]: Please remove this comment, nothing is required for other profile now.

File: src/gen8_mfc.c [hunk 3]
```diff
@@ -4529,7 +4533,7 @@ static VAStatus gen8_mfc_pipeline(VADriverContextP ctx,
         vaStatus = gen8_mfc_avc_encode_picture(ctx, encode_state, encoder_context);
         break;
 
-        /* FIXME: add for other profile */
+    /* FIXME: add for other profile */
```
Comment (xhaihao) [inline src/gen8_mfc.c]: Please remove this comment, nothing is required for other profile now.
